import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../comps/Card";

const Home = () => {
  const [data, setData] = useState([]);

  const filter = (e) => {
    const res = data.filter((dat) => {
      return (
        dat.role == e ||
        dat.level == e ||
        dat.languages.includes(e) ||
        dat.tools.includes(e)
      );
    });
    setData(res);
  };

  useEffect(() => {
    fetch("/data.json")
      .then((res) => res.json())
      .then((data) => {
        setData(data);
      })
      .catch((err) => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Frontend Mentor | Job Listings with Filtering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="head-img"></div>
      <div className="card-div">
        {data.map((dat) => (
          <Card
            key={dat.id}
            src={dat.logo}
            alt={dat.company}
            name={dat.company}
            title={dat.position}
            new={dat.new}
            featured={dat.featured}
            tags={`${dat.postedAt} • ${dat.contract} • ${dat.location}`}
            stacks={[dat.role, dat.level, ...dat.languages, ...dat.tools]}
            callback={filter}
          />
        ))}
      </div>
    </>
  );
};

export default Home;
